include API

diff --git a/.github/workflows/Analysis.yml b/.github/workflows/Analysis.yml
--- a/.github/workflows/Analysis.yml
+++ b/.github/workflows/Analysis.yml
@@ -3,11 +3,11 @@ name: Check testcases and quality gate status
 on:
   push:
     branches:
-      - '*'
-  
-  pull_request: 
+      - "*"
+
+  pull_request:
     branches:
-      - '*'
+      - "*"
 
 jobs:
   sonarqube-analysis:
@@ -32,15 +32,15 @@ jobs:
 
       - name: Check test exit code
         run: |
-            if [ $exit_code -ne 0 ]; then
-                echo "Test cases failed !! Exiting..."
-                exit 1
-              else
-                echo "cheers up, all Test cases are passed !!"
-              fi
+          if [ $exit_code -ne 0 ]; then
+              echo "Test cases failed !! Exiting..."
+              exit 1
+            else
+              echo "cheers up, all Test cases are passed !!"
+            fi
 
-      - name: Set branch name        
-        id: set_branch        
+      - name: Set branch name
+        id: set_branch
         run: |
           if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
             BRANCH_NAME=${GITHUB_BASE_REF}
@@ -48,7 +48,7 @@ jobs:
             BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
             fi
             echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
-      
+
       - name: Scanning the project with sonarQube scanner
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -74,13 +74,3 @@ jobs:
               else
                 echo "SonarQube Quality Gate passed !!" 
               fi
-              - name: HTTP Request to SonarQube
-              id: sonarqube_request
-              uses: actions/http-request@v2
-              with:
-                url: https://sonarqube.kcspl.in/api/qualitygates/project_status?projectKey=Ecard_Ecard&pullRequest=${{ steps.pr_number.outputs.pr_number }}
-                headers: |
-                  ${{ secrets.YOUR_AUTHORIZATION_HEADERS }}  # Replace with your actual authorization headers
-      
-            - name: Output SonarQube Response
-              run: echo "${{ steps.sonarqube_request.outputs.body }}"    
