include API

diff --git a/.github/workflows/Analysis.yml b/.github/workflows/Analysis.yml
--- a/.github/workflows/Analysis.yml
+++ b/.github/workflows/Analysis.yml
@@ -64,13 +64,23 @@ jobs:
             -Dsonar.branch.name=$BRANCH_NAME
 
       - name: identify SonarQube Quality Gate status
+        id: quality_gate_status
         run: |
           echo "Identifying quality gate status..."
-          STATUS=$(curl -s "${{secrets.SERVER_URL}}/api/qualitygates/project_status?projectKey=${{secrets.PROJECT_KEY}}" -u "${{secrets.LOGIN_TOKEN}}" | jq -r '.projectStatus.status')
-          echo "$STATUS"  
-            if [ "$STATUS" != "OK" ]; then
-              echo "SonarQube Quality Gate Failed !!"
-              exit 1
-              else
-                echo "SonarQube Quality Gate passed !!" 
-              fi
+          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+            BRANCH_NAME=${GITHUB_BASE_REF}
+          else
+            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
+          fi
+          STATUS=$(curl -s "${{secrets.SERVER_URL}}/api/qualitygates/project_status?projectKey=${{secrets.PROJECT_KEY}}&branch=${BRANCH_NAME}" -u "${{secrets.LOGIN_TOKEN}}" | jq -r '.projectStatus.status')
+          echo "Quality Gate Status for branch $BRANCH_NAME: $STATUS"
+          echo "QUALITY_GATE_STATUS=$STATUS" >> $GITHUB_ENV
+
+      - name: Check Quality Gate status
+        run: |
+          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+            echo "SonarQube Quality Gate Failed for branch $BRANCH_NAME!!"
+            exit 1
+          else
+            echo "SonarQube Quality Gate passed for branch $BRANCH_NAME!!"
+          fi
