update YAML

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,8 +24,17 @@ jobs:
       - name: Run testcases with generatig coverage report
         run: |
           npm test --coverage --coverageReporters=text-lcov | tee coverage.lcov
-          echo $?
+          echo "::set-output name=exit_code::${PIPESTATUS[0]}"
 
+          - name: Check test exit code
+            run: |
+              TEST_EXIT_CODE=${{ steps.test.outputs.exit_code }}
+              if [ $TEST_EXIT_CODE -ne 0 ]; then
+                echo "Test cases failed. Exiting..."
+                exit 1
+              else
+                echo "Test cases passed."
+              fi
       - name: Scanning the project with sonarQube scanner
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
