update yAML

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,12 @@ jobs:
         run: npm install
 
       - name: Run testcases with generatig coverage report
-        run: npm test --coverage --coverageReporters=text-lcov | tee coverage.lcov
+        run: |
+          npm test --coverage --coverageReporters=text-lcov | tee coverage.lcov
+          if [ $? -ne 0 ]; then
+            echo "Tests failed, failing the workflow."
+            exit 1
+          fi
 
       - name: Scanning the project with sonarQube scanner
         env:
