update yAML

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: SonarQube Analysis
+name: Check testcases and quality gate status
 
 on:
   push:
@@ -16,15 +16,15 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '14'
+          node-version: "14"
 
       - name: Install dependencies
         run: npm install
 
-      - name: Run tests with coverage
+      - name: Run testcases with generatig coverage
         run: npm test --coverage --coverageReporters=text-lcov | tee coverage.lcov
 
-      - name: SonarQube Scan
+      - name: Scanning the project with sonarQube scanner
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
@@ -36,3 +36,15 @@ jobs:
             -Dsonar.test.inclusions=test/index.test.js \
             -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
             -Dsonar.login=82937a40b7dbb37782bacb338c7bca84a24196e9
+
+      - name: identify SonarQube Quality Gate status
+        run: |
+          echo "Identifying quality gate status..."
+            STATUS=$(curl -s "http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=QulityGateTest" -u "4bfeceb86030431b89e0f94ac01e996405e8f016" | jq -r '.projectStatus.status')
+             
+            if [ "$STATUS" != "OK" ]; then
+              echo "SonarQube Quality Gate Failed !!"
+              exit 1
+              else
+                echo "SonarQube Quality Gate passed !!" 
+              fi
