update yAML

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,8 +21,14 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Run testcases with generatig coverage
-        run: npm test --coverage --coverageReporters=text-lcov | tee coverage.lcov
+      - name: Run testcases with generatig coverage report
+        run: |
+          npm test -- --coverage --coverageReporters=text-lcov | tee coverage.lcov
+          test_exit_code=$?
+          if [ $test_exit_code -ne 0 ]; then
+            echo "Tests failed, failing the workflow."
+          exit $test_exit_code
+          fi
 
       - name: Scanning the project with sonarQube scanner
         env:
